### ISSUE TITLE
我将receiver.php文件放到了我本地的一个服务器上 然后上传 出现了如下错误 该咋办

### ISSUE THREAD

**Issue by w2230030100** [fex-team/fis-command-release#14]
```
bogon:kelepc ningfujun$ fisp release -d remote

 Ω ................................................................ 118ms
/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:63
        throw err
              ^
Error: upload file [/page/layout.tpl] to [/kelepc/fis/www] by receiver [http://127.0.0.1/fisr/fis-command-release/tools/receiver.php] error [1]
    at Object.exports.error (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at /usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-deploy-default/index.js:76:25
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/util.js:835:21)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
到底我哪里出错了

**Comment by xiangshouding** [comment]
- 远端有这个目录吗 `/kelepc/fis/www` 是否有权限写？

**Comment by w2230030100** [comment]
@xiangshouding 设置了读写了 有目录 还是不行
```
bogon:kelepc ningfujun$ fisp release -d remote

 Ω ................................................................ 111ms
/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:63
        throw err
              ^
Error: upload file [/page/layout.tpl] to [/kelepc/fis/www] by receiver [http://127.0.0.1/fisr/fis-command-release/tools/receiver.php] error [1]
    at Object.exports.error (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at /usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-deploy-default/index.js:76:25
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/util.js:835:21)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by xiangshouding** [comment]
`/kelepc/fis/www` 在这个目录下执行 `pwd` 命令，让我看看

**Comment by xiangshouding** [comment]
如果这些都 OK，请检查磁盘 `/tmp` 目录下是否满了，具体做法请咨询 Google

**Comment by w2230030100** [comment]
话说pwd命令是干啥的 我打了个这个您看是这样么
```
/Users/ningfujun/work/Dakele/kelepc/fis/www
bogon:www ningfujun$ pwd
/Users/ningfujun/work/Dakele/kelepc/fis/www
bogon:www ningfujun$ pwd -p
-bash: pwd: -p: invalid option
pwd: usage: pwd [-LP]
bogon:www ningfujun$ pwd -l
-bash: pwd: -l: invalid option
pwd: usage: pwd [-LP]
bogon:www ningfujun$ pwd -L
/Users/ningfujun/work/Dakele/kelepc/fis/www
bogon:www ningfujun$ pwd -P
/Users/ningfujun/work/Dakele/kelepc/fis/www
bogon:www ningfujun$ pwd -LP
/Users/ningfujun/work/Dakele/kelepc/fis/www
bogon:www ningfujun$ 
```

**Comment by w2230030100** [comment]
![image](https://cloud.githubusercontent.com/assets/6111324/7997719/5c497f5c-0b64-11e5-8f51-c01c05d9b55b.png)

**Comment by xiangshouding** [comment]
`/Users/ningfujun/work/Dakele/kelepc/fis/www` 写相对于系统根目录的地址

**Comment by w2230030100** [comment]
@xiangshouding  谢谢大神 能传上去了
但是怎么自动化打包啊 就是类似fis的那种针对单页面进行1个css和1个js的那种 我看教程有个自动化的链接是这个http://solar.baidu.com/autopack/doc 但是打不开

**Comment by xiangshouding** [comment]
@w2230030100 fisp 里面的合并打包看这个地方

http://oak.baidu.com/fis-plus/document.html#%25E6%2589%2593%25E5%258C%2585%25E5%2590%2588%25E5%25B9%25B6

**Comment by w2230030100** [comment]
@xiangshouding 不提供自动打包吗

**Comment by xiangshouding** [comment]
@w2230030100 自动打包还未开源，像 `fis-postpackager-simple` 插件一样的静态式合并不适合后端模板项目。

**Comment by w2230030100** [comment]
@xiangshouding jello支持单页面的自动打包吗

**Comment by w2230030100** [comment]
![image](https://cloud.githubusercontent.com/assets/6111324/7998820/56241eec-0b74-11e5-8e20-1b572b58a41a.png)
而且我发现教程这一块是写错了吗 是不是应该是/template
