### ISSUE TITLE
fis2上传文件到服务器死活上传不了

### ISSUE THREAD

**Issue by wonyun** [fex-team/fis-command-release#25]
/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/log.js:63
        throw err
        ^

Error: upload file [/build.sh] to [/home/xiaoju/webroot/bus-webapp] by receiver [http://10.94.96.212:9099/receiver.php] error [1]
    at Object.exports.error (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at /usr/local/lib/node_modules/fis/node_modules/fis-deploy-default/index.js:76:25
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:836:21)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)

**Comment by wonyun** [comment]
@xiangshouding

**Comment by xiangshouding** [comment]
目标目录没权限，特别是你放接收端的服务器没权限。具体你再看看

**Comment by wonyun** [comment]
@xiangshouding 之前特意对服务器上接受文件的目录加了777权限的，还是有这个问题。
>特别是你放接收端的服务器没权限

服务器是以root权限登录的，貌似有权限呢

**Comment by xiangshouding** [comment]
/home/xiaoju/webroot 整个 webroot 加上呢

chmod -R 777 /home/xiaoju/webroot
